use std::collections::HashMap;
use std::ffi::{CStr, CString};
use std::os::raw::c_void;
use std::sync::atomic::{AtomicBool, Ordering};

use duckdb::{
    core::{DataChunkHandle, Inserter, LogicalTypeHandle, LogicalTypeId},
    vtab::{BindInfo, InitInfo, TableFunctionInfo, VTab, Value},
};
use libduckdb_sys as ffi;

use crate::catalog::CatalogState;
use crate::expand::{expand, suggest_closest, QueryRequest};
use crate::model::SemanticViewDefinition;

use super::error::QueryError;

// ---------------------------------------------------------------------------
// QueryState -- stored as extra_info on the table function
// ---------------------------------------------------------------------------

/// Shared state for the `semantic_query` table function.
///
/// Carries the catalog (in-memory view definitions) and a raw `duckdb_connection`
/// handle for executing expanded SQL via the C API. The connection is created
/// independently of the host connection by calling `duckdb_connect` on the same
/// database handle, avoiding lock conflicts with the host during query execution.
///
/// For the connection handle extraction strategy, see `extract_query_conn` in lib.rs.
#[derive(Clone)]
pub struct QueryState {
    pub catalog: CatalogState,
    /// Raw connection handle for SQL execution.
    pub conn: ffi::duckdb_connection,
}

// SAFETY: The `duckdb_connection` raw pointer is an opaque handle managed by DuckDB.
// It was created during `extension_entrypoint` and lives for the database session lifetime.
// DuckDB manages internal synchronization for connections.
unsafe impl Send for QueryState {}
unsafe impl Sync for QueryState {}

// ---------------------------------------------------------------------------
// BindData / InitData
// ---------------------------------------------------------------------------

/// Data computed at bind time: the expanded SQL, output schema, and metadata.
pub struct SemanticViewBindData {
    /// The SQL query generated by `expand()`, ready for execution.
    expanded_sql: String,
    /// Output column names (dimensions first, then metrics).
    column_names: Vec<String>,
    /// DuckDB type enums (as u32) for each output column, parallel to column_names.
    /// `DUCKDB_TYPE_INVALID` (0) signals VARCHAR fallback for that column.
    column_type_ids: Vec<u32>,
}

// SAFETY: All fields are `Send + Sync` types.
unsafe impl Send for SemanticViewBindData {}
unsafe impl Sync for SemanticViewBindData {}

/// State tracked during function execution.
pub struct SemanticViewInitData {
    /// Signals when all rows have been emitted.
    done: AtomicBool,
}

// SAFETY: `AtomicBool` is `Send + Sync`.
unsafe impl Send for SemanticViewInitData {}
unsafe impl Sync for SemanticViewInitData {}

// ---------------------------------------------------------------------------
// FFI helpers
// ---------------------------------------------------------------------------

/// Execute a SQL string via the DuckDB C API and return the result.
///
/// The caller is responsible for calling `duckdb_destroy_result` on the returned
/// result when done.
///
/// # Safety
///
/// `conn` must be a valid, non-null `duckdb_connection` handle.
pub(crate) unsafe fn execute_sql_raw(
    conn: ffi::duckdb_connection,
    sql: &str,
) -> Result<ffi::duckdb_result, String> {
    let sql_cstr = CString::new(sql).map_err(|e| e.to_string())?;
    let mut result: ffi::duckdb_result = std::mem::zeroed();
    let rc = ffi::duckdb_query(conn, sql_cstr.as_ptr(), &mut result);
    if rc != ffi::DuckDBSuccess {
        let err_ptr = ffi::duckdb_result_error(&mut result);
        let err_msg = if err_ptr.is_null() {
            "unknown error".to_string()
        } else {
            CStr::from_ptr(err_ptr).to_string_lossy().into_owned()
        };
        ffi::duckdb_destroy_result(&mut result);
        return Err(err_msg);
    }
    Ok(result)
}

/// Extract the raw `duckdb_value` pointer from a `duckdb::vtab::Value`.
///
/// The `Value` struct has a single field `ptr: duckdb_value` (which is `*mut c_void`),
/// but it is `pub(crate)` and inaccessible from external crates.  Since both types
/// are exactly one pointer wide, transmute is a safe layout conversion.
///
/// The returned pointer is valid only for the lifetime of the `Value` (it is NOT
/// destroyed; the `Value` still owns it).
///
/// # Safety
///
/// Relies on `duckdb::vtab::Value` layout being a single `duckdb_value` field.
/// This is stable for `duckdb = "=1.4.4"`.
unsafe fn value_raw_ptr(value: &Value) -> ffi::duckdb_value {
    // Value is repr(Rust) with one field: duckdb_value (*mut c_void).
    // Reading the pointer without taking ownership.
    let ptr_to_value = std::ptr::from_ref(value).cast::<ffi::duckdb_value>();
    std::ptr::read(ptr_to_value)
}

/// Extract string elements from a DuckDB LIST(VARCHAR) value.
///
/// Uses the C API `duckdb_get_list_size` and `duckdb_get_list_child` to iterate
/// the list, then `duckdb_get_varchar` on each child element.
///
/// # Safety
///
/// `value` must represent a LIST(VARCHAR) value.
pub(crate) unsafe fn extract_list_strings(value: &Value) -> Vec<String> {
    let value_ptr = value_raw_ptr(value);
    let size = ffi::duckdb_get_list_size(value_ptr);
    let mut result = Vec::with_capacity(size as usize);
    for i in 0..size {
        let child = ffi::duckdb_get_list_child(value_ptr, i);
        let cstr = ffi::duckdb_get_varchar(child);
        if !cstr.is_null() {
            let s = CStr::from_ptr(cstr).to_string_lossy().into_owned();
            ffi::duckdb_free(cstr.cast::<c_void>());
            result.push(s);
        }
        ffi::duckdb_destroy_value(&mut { child });
    }
    result
}

/// Extract key-value pairs from a DuckDB MAP(VARCHAR, VARCHAR) named parameter value.
///
/// Returns a `HashMap` with all keys lowercased for case-insensitive dimension name
/// matching. Only entries where both key and value are non-null are inserted.
///
/// # Safety
///
/// `value` must represent a MAP(VARCHAR, VARCHAR) value.
unsafe fn extract_map_strings(value: &Value) -> HashMap<String, String> {
    let value_ptr = value_raw_ptr(value);
    let size = ffi::duckdb_get_map_size(value_ptr);
    let mut result = HashMap::with_capacity(size as usize);
    for i in 0..size {
        let mut key = ffi::duckdb_get_map_key(value_ptr, i);
        let mut val = ffi::duckdb_get_map_value(value_ptr, i);
        let k_cstr = ffi::duckdb_get_varchar(key);
        let v_cstr = ffi::duckdb_get_varchar(val);
        if !k_cstr.is_null() && !v_cstr.is_null() {
            let k = CStr::from_ptr(k_cstr).to_string_lossy().into_owned();
            let v = CStr::from_ptr(v_cstr).to_string_lossy().into_owned();
            ffi::duckdb_free(k_cstr.cast::<c_void>());
            ffi::duckdb_free(v_cstr.cast::<c_void>());
            result.insert(k.to_ascii_lowercase(), v);
        }
        ffi::duckdb_destroy_value(&mut key);
        ffi::duckdb_destroy_value(&mut val);
    }
    result
}

// ---------------------------------------------------------------------------
// Type mapping helpers
// ---------------------------------------------------------------------------

/// Typed value enum for accumulating column data across chunks before writing to output.
enum TypedValue {
    Null,
    I64(i64),    // BIGINT, UBIGINT, HUGEINT (truncated), SMALLINT upcast, etc.
    I32(i32),    // INTEGER, DATE (days-since-epoch), SMALLINT, TINYINT
    F64(f64),    // DOUBLE, FLOAT upcast
    Str(String), // VARCHAR, all other types (fallback)
}

/// Convert a raw `ffi::duckdb_type` (u32) to a `LogicalTypeHandle`.
///
/// Complex types (LIST, STRUCT, MAP, ENUM) and DECIMAL fall back to VARCHAR/DOUBLE.
/// INVALID (0) falls back to VARCHAR.
fn type_from_duckdb_type_u32(t: u32) -> LogicalTypeHandle {
    // Named constants matching libduckdb-sys DUCKDB_TYPE_DUCKDB_TYPE_* values.
    const INVALID: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_INVALID;
    const DECIMAL: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_DECIMAL;
    const ENUM: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_ENUM;
    const LIST: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_LIST;
    const STRUCT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_STRUCT;
    const MAP: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_MAP;
    // 128-bit integer types: DuckDB HUGEINT/UHUGEINT use 16 bytes per slot.
    // We write them as i64 (8 bytes) via parse_typed_from_str, so declare
    // the output column as BIGINT to match the write operation size.
    const HUGEINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_HUGEINT;
    const UHUGEINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_UHUGEINT;
    match t {
        // Complex types and DECIMAL fall back to VARCHAR.
        // DECIMAL is kept as VARCHAR to preserve exact precision formatting
        // (e.g., "350.00" instead of "350.0") and to avoid needing the scale
        // metadata for correct parsing in func().
        INVALID | DECIMAL | ENUM | LIST | STRUCT | MAP => {
            LogicalTypeHandle::from(LogicalTypeId::Varchar)
        }
        // HUGEINT/UHUGEINT are 16-byte types; we store them as i64 (BIGINT slot size).
        // Declaring output as BIGINT avoids writing 8 bytes into a 16-byte slot.
        HUGEINT | UHUGEINT => LogicalTypeHandle::from(LogicalTypeId::Bigint),
        _ => LogicalTypeHandle::from(LogicalTypeId::from(t)),
    }
}

// ---------------------------------------------------------------------------
// VTab implementation
// ---------------------------------------------------------------------------

/// The `semantic_query` table function.
///
/// Registered as a single generic function that accepts a view name as a
/// positional parameter and optional `dimensions` / `metrics` as named
/// `LIST(VARCHAR)` parameters.
///
/// Usage:
/// ```sql
/// FROM semantic_query('my_view', dimensions := ['region'], metrics := ['total_revenue'])
/// ```
pub struct SemanticViewVTab;

impl VTab for SemanticViewVTab {
    type BindData = SemanticViewBindData;
    type InitData = SemanticViewInitData;

    fn bind(bind: &BindInfo) -> Result<Self::BindData, Box<dyn std::error::Error>> {
        // 1. Extract the view name (positional parameter 0).
        let view_name = bind.get_parameter(0).to_string();

        // 2. Extract dimensions and metrics from named LIST(VARCHAR) parameters.
        //    Use the raw duckdb_value FFI to iterate list elements.
        let dimensions = match bind.get_named_parameter("dimensions") {
            Some(ref val) => unsafe { extract_list_strings(val) },
            None => vec![],
        };
        let metrics = match bind.get_named_parameter("metrics") {
            Some(ref val) => unsafe { extract_list_strings(val) },
            None => vec![],
        };

        // Extract optional granularities MAP(VARCHAR, VARCHAR) for query-time override (TIME-03).
        let granularity_overrides: HashMap<String, String> =
            match bind.get_named_parameter("granularities") {
                Some(ref val) => unsafe { extract_map_strings(val) },
                None => HashMap::new(),
            };

        // 3. Validate: at least one dimension or metric.
        if dimensions.is_empty() && metrics.is_empty() {
            return Err(Box::new(QueryError::EmptyRequest {
                view_name: view_name.clone(),
            }));
        }

        // 4. Look up view definition in the catalog.
        let state_ptr = bind.get_extra_info::<QueryState>();
        let state = unsafe { &*state_ptr };
        let catalog_guard = state.catalog.read().expect("catalog RwLock poisoned");

        let json_str = match catalog_guard.get(&view_name) {
            Some(j) => j.clone(),
            None => {
                let available: Vec<String> = catalog_guard.keys().cloned().collect();
                let suggestion = suggest_closest(&view_name, &available);
                return Err(Box::new(QueryError::ViewNotFound {
                    name: view_name,
                    suggestion,
                    available,
                }));
            }
        };
        // Release the catalog lock before proceeding.
        drop(catalog_guard);

        // 5. Parse definition and expand.
        let def = SemanticViewDefinition::from_json(&view_name, &json_str)
            .map_err(|e| -> Box<dyn std::error::Error> { e.into() })?;

        // Validate granularity overrides against the view definition (TIME-03).
        const VALID_GRANULARITIES: &[&str] = &["day", "week", "month", "year"];
        for (override_dim_lower, override_gran) in &granularity_overrides {
            if let Some(dim_def) = def
                .dimensions
                .iter()
                .find(|d| d.name.to_ascii_lowercase() == *override_dim_lower)
            {
                if dim_def.dim_type.as_deref() != Some("time") {
                    return Err(format!(
                        "dimension '{}' is not a time dimension and cannot have a granularity override",
                        dim_def.name
                    )
                    .into());
                }
                if !VALID_GRANULARITIES.contains(&override_gran.as_str()) {
                    return Err(format!(
                        "granularity override '{}' for dimension '{}' is not supported; valid values: {}",
                        override_gran,
                        dim_def.name,
                        VALID_GRANULARITIES.join(", ")
                    )
                    .into());
                }
            }
            // If dimension doesn't exist in the view at all, expand() will catch it as UnknownDimension.
        }

        let req = QueryRequest {
            dimensions: dimensions.clone(),
            metrics: metrics.clone(),
            granularity_overrides,
        };
        let expanded_sql = expand(&view_name, &def, &req)
            .map_err(|e| -> Box<dyn std::error::Error> { Box::new(QueryError::from(e)) })?;

        // 6. Resolve output column names and types.
        //    Primary path: use DDL-time stored type data (column_type_names + column_types_inferred).
        //    Fallback path: run LIMIT 0 at bind time (in-memory DB or inference failed at DDL time).
        //    Full fallback: derive names from definition, all VARCHAR.
        let type_map: HashMap<String, u32> = def
            .column_type_names
            .iter()
            .zip(def.column_types_inferred.iter())
            .map(|(name, &t)| (name.to_ascii_lowercase(), t))
            .collect();

        let (column_names, column_type_ids) = if !type_map.is_empty() {
            // Primary path: DDL-time inference stored both names and types.
            // Derive column names from requested dims+metrics (expand() order),
            // look up each name in the DDL-time type map. No LIMIT 0 at query time.
            let mut names = Vec::new();
            let mut type_ids = Vec::new();
            for dim_name in &dimensions {
                let canonical = def
                    .dimensions
                    .iter()
                    .find(|d| d.name.eq_ignore_ascii_case(dim_name))
                    .map_or_else(|| dim_name.clone(), |d| d.name.clone());
                let t = *type_map
                    .get(&canonical.to_ascii_lowercase())
                    .unwrap_or(&0u32);
                names.push(canonical);
                type_ids.push(t);
            }
            for met_name in &metrics {
                let canonical = def
                    .metrics
                    .iter()
                    .find(|m| m.name.eq_ignore_ascii_case(met_name))
                    .map_or_else(|| met_name.clone(), |m| m.name.clone());
                let t = *type_map
                    .get(&canonical.to_ascii_lowercase())
                    .unwrap_or(&0u32);
                names.push(canonical);
                type_ids.push(t);
            }
            (names, type_ids)
        } else {
            // Fallback path: in-memory DB or DDL inference failed.
            // Run try_infer_schema on the per-query expanded SQL (bind-time, safe on state.conn).
            let limit0_sql = format!("{expanded_sql} LIMIT 0");
            if let Some((names, types)) = unsafe { try_infer_schema(state.conn, &limit0_sql) } {
                let type_ids: Vec<u32> = types.iter().map(|t| *t as u32).collect();
                (names, type_ids)
            } else {
                // Full fallback: derive names from definition, all VARCHAR (0 = INVALID).
                let mut names = Vec::new();
                for dim_name in &dimensions {
                    let canonical = def
                        .dimensions
                        .iter()
                        .find(|d| d.name.eq_ignore_ascii_case(dim_name))
                        .map_or_else(|| dim_name.clone(), |d| d.name.clone());
                    names.push(canonical);
                }
                for met_name in &metrics {
                    let canonical = def
                        .metrics
                        .iter()
                        .find(|m| m.name.eq_ignore_ascii_case(met_name))
                        .map_or_else(|| met_name.clone(), |m| m.name.clone());
                    names.push(canonical);
                }
                let type_ids = vec![0u32; names.len()];
                (names, type_ids)
            }
        };

        // 7. Declare typed output columns.
        //    type_from_duckdb_type_u32 maps complex/invalid types to VARCHAR fallback.
        for (name, &type_id) in column_names.iter().zip(column_type_ids.iter()) {
            bind.add_result_column(name, type_from_duckdb_type_u32(type_id));
        }

        Ok(SemanticViewBindData {
            expanded_sql,
            column_names,
            column_type_ids,
        })
    }

    fn init(_: &InitInfo) -> Result<Self::InitData, Box<dyn std::error::Error>> {
        Ok(SemanticViewInitData {
            done: AtomicBool::new(false),
        })
    }

    fn func(
        func: &TableFunctionInfo<Self>,
        output: &mut DataChunkHandle,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let init_data = func.get_init_data();

        // If already done, signal completion.
        if init_data.done.swap(true, Ordering::Relaxed) {
            output.set_len(0);
            return Ok(());
        }

        let bind_data = func.get_bind_data();
        let state = unsafe { &*func.get_extra_info::<QueryState>() };

        // Execute with a VARCHAR cast wrapper to guarantee uniform string layout in
        // result chunks. This handles all DuckDB types (DECIMAL, HUGEINT, complex types)
        // without requiring type-specific binary chunk parsing.
        // Typed columns are written via parse_typed_from_str() after reading the strings.
        let varchar_sql = build_varchar_cast_sql(&bind_data.expanded_sql, &bind_data.column_names);

        let mut result = unsafe {
            execute_sql_raw(state.conn, &varchar_sql).map_err(|e| QueryError::SqlExecution {
                expanded_sql: bind_data.expanded_sql.clone(),
                duckdb_error: e,
            })?
        };

        let col_count = unsafe { ffi::duckdb_column_count(&mut result) } as usize;
        let chunk_count = unsafe { ffi::duckdb_result_chunk_count(result) } as usize;

        // Collect all rows as string vectors (column-major for efficient typed writes).
        let mut total_rows = 0usize;
        let mut col_strings: Vec<Vec<String>> = vec![Vec::new(); col_count];

        for chunk_idx in 0..chunk_count {
            let chunk = unsafe { ffi::duckdb_result_get_chunk(result, chunk_idx as ffi::idx_t) };
            if chunk.is_null() {
                continue;
            }
            let row_count = unsafe { ffi::duckdb_data_chunk_get_size(chunk) } as usize;
            total_rows += row_count;

            for col_idx in 0..col_count {
                for row_idx in 0..row_count {
                    let s = unsafe { read_varchar_from_vector(chunk, col_idx, row_idx) };
                    col_strings[col_idx].push(s);
                }
            }

            unsafe {
                ffi::duckdb_destroy_data_chunk(&mut { chunk });
            }
        }

        // Write typed output: parse string values to the appropriate typed vectors.
        if total_rows > 0 {
            for col_idx in 0..col_count.min(bind_data.column_names.len()) {
                let type_id = if col_idx < bind_data.column_type_ids.len() {
                    bind_data.column_type_ids[col_idx]
                } else {
                    0
                };
                let col_data: Vec<TypedValue> = col_strings[col_idx]
                    .iter()
                    .map(|s| parse_typed_from_str(s, type_id))
                    .collect();
                write_typed_column(output, col_idx, &col_data, total_rows, type_id);
            }
        }
        output.set_len(total_rows);

        unsafe {
            ffi::duckdb_destroy_result(&mut result);
        }

        Ok(())
    }

    fn parameters() -> Option<Vec<LogicalTypeHandle>> {
        // Positional parameter: view_name (VARCHAR)
        Some(vec![LogicalTypeHandle::from(LogicalTypeId::Varchar)])
    }

    fn named_parameters() -> Option<Vec<(String, LogicalTypeHandle)>> {
        Some(vec![
            (
                "dimensions".to_string(),
                LogicalTypeHandle::list(&LogicalTypeHandle::from(LogicalTypeId::Varchar)),
            ),
            (
                "metrics".to_string(),
                LogicalTypeHandle::list(&LogicalTypeHandle::from(LogicalTypeId::Varchar)),
            ),
            // granularities: query-time granularity override map (TIME-03)
            // MAP(VARCHAR, VARCHAR) — e.g., granularities := {'order_date': 'month'}
            (
                "granularities".to_string(),
                LogicalTypeHandle::map(
                    &LogicalTypeHandle::from(LogicalTypeId::Varchar),
                    &LogicalTypeHandle::from(LogicalTypeId::Varchar),
                ),
            ),
        ])
    }
}

// ---------------------------------------------------------------------------
// Schema inference
// ---------------------------------------------------------------------------

/// Attempt to infer column names and types by executing a LIMIT 0 query.
///
/// Returns `None` if the query fails for any reason.
///
/// # Safety
///
/// `conn` must be a valid `duckdb_connection`.
pub(crate) unsafe fn try_infer_schema(
    conn: ffi::duckdb_connection,
    sql: &str,
) -> Option<(Vec<String>, Vec<ffi::duckdb_type>)> {
    let mut result = execute_sql_raw(conn, sql).ok()?;

    let col_count = ffi::duckdb_column_count(&mut result) as usize;
    let mut names = Vec::with_capacity(col_count);
    let mut types = Vec::with_capacity(col_count);

    for i in 0..col_count {
        let name_ptr = ffi::duckdb_column_name(&mut result, i as ffi::idx_t);
        let name = if name_ptr.is_null() {
            format!("column{i}")
        } else {
            CStr::from_ptr(name_ptr).to_string_lossy().into_owned()
        };
        names.push(name);

        let ty = ffi::duckdb_column_type(&mut result, i as ffi::idx_t);
        types.push(ty);
    }

    ffi::duckdb_destroy_result(&mut result);
    Some((names, types))
}

// ---------------------------------------------------------------------------
// VARCHAR-cast SQL wrapping and chunk-based string reading
// ---------------------------------------------------------------------------

/// Wrap the expanded SQL in a subquery that casts every output column to VARCHAR.
///
/// The deprecated `duckdb_value_varchar` API does not work reliably with DuckDB's
/// chunked result format. By casting all columns to VARCHAR in the SQL itself,
/// we guarantee that every vector in every result chunk contains `duckdb_string_t`
/// values, which can be read uniformly via `read_varchar_from_vector`.
fn build_varchar_cast_sql(expanded_sql: &str, column_names: &[String]) -> String {
    use crate::expand::quote_ident;

    let cast_items: Vec<String> = column_names
        .iter()
        .map(|name| {
            format!(
                "CAST({} AS VARCHAR) AS {}",
                quote_ident(name),
                quote_ident(name)
            )
        })
        .collect();
    format!(
        "SELECT {} FROM ({}) AS \"_sq\"",
        cast_items.join(", "),
        expanded_sql
    )
}

/// Read a VARCHAR value from a data chunk vector at the given column and row.
///
/// The vector must contain VARCHAR (`duckdb_string_t`) data. Returns an empty
/// string for NULL values.
///
/// Decodes the `duckdb_string_t` layout directly from vector memory to avoid
/// reliance on C API helper functions that may not be available in loadable
/// extension mode.
///
/// # Safety
///
/// `chunk` must be a valid, non-null `duckdb_data_chunk` handle.
/// `col_idx` and `row_idx` must be within bounds.
#[allow(clippy::cast_possible_truncation)]
pub(crate) unsafe fn read_varchar_from_vector(
    chunk: ffi::duckdb_data_chunk,
    col_idx: usize,
    row_idx: usize,
) -> String {
    let vector = ffi::duckdb_data_chunk_get_vector(chunk, col_idx as ffi::idx_t);

    // Check for NULL using the validity mask.
    let validity = ffi::duckdb_vector_get_validity(vector);
    if !validity.is_null() {
        let entry_idx = row_idx / 64;
        let bit_idx = row_idx % 64;
        let entry = *validity.add(entry_idx);
        if entry & (1u64 << bit_idx) == 0 {
            return String::new(); // NULL
        }
    }

    // Read the duckdb_string_t from the vector data.
    // Layout is a 16-byte union:
    //   Inline  (len <= 12): { length: u32, inlined: [c_char; 12] }
    //   Pointer (len > 12):  { length: u32, prefix: [c_char; 4], ptr: *mut c_char }
    let data_ptr = ffi::duckdb_vector_get_data(vector);
    let string_t_ptr = data_ptr.cast::<ffi::duckdb_string_t>().add(row_idx);
    let string_t = &*string_t_ptr;

    // The length field is at the same offset for both union variants.
    let len = string_t.value.inlined.length as usize;
    if len == 0 {
        return String::new();
    }

    let bytes = if len <= 12 {
        // Inline: string data follows the length field directly.
        let inline_ptr = string_t.value.inlined.inlined.as_ptr().cast::<u8>();
        std::slice::from_raw_parts(inline_ptr, len)
    } else {
        // Pointer: data is at the heap-allocated ptr.
        let heap_ptr = string_t.value.pointer.ptr.cast::<u8>();
        if heap_ptr.is_null() {
            return String::new();
        }
        std::slice::from_raw_parts(heap_ptr, len)
    };

    String::from_utf8_lossy(bytes).into_owned()
}

// ---------------------------------------------------------------------------
// Typed column parse/write helpers
// ---------------------------------------------------------------------------

/// Parse a YYYY-MM-DD date string into days since the Unix epoch (1970-01-01).
///
/// Returns `None` if the string is not a valid YYYY-MM-DD date.
/// DuckDB's `duckdb_date` (stored as `i32` in FlatVector) counts days since
/// 1970-01-01 (negative for dates before epoch).
fn date_str_to_epoch_days(s: &str) -> Option<i32> {
    // Expect exactly "YYYY-MM-DD" (10 bytes).
    if s.len() != 10 || &s[4..5] != "-" || &s[7..8] != "-" {
        return None;
    }
    let year: i32 = s[0..4].parse().ok()?;
    let month: i32 = s[5..7].parse().ok()?;
    let day: i32 = s[8..10].parse().ok()?;

    // Use the proleptic Gregorian calendar formula (Julian Day Number approach).
    // Days since epoch = JDN(date) - JDN(1970-01-01)
    // JDN(1970-01-01) = 2440588
    fn jdn(y: i32, m: i32, d: i32) -> i32 {
        // Algorithm from Astronomical Algorithms (Meeus), valid for Gregorian calendar.
        let a = (14 - m) / 12;
        let yy = y + 4800 - a;
        let mm = m + 12 * a - 3;
        d + (153 * mm + 2) / 5 + 365 * yy + yy / 4 - yy / 100 + yy / 400 - 32045
    }

    const JDN_EPOCH: i32 = 2_440_588; // JDN for 1970-01-01
    Some(jdn(year, month, day) - JDN_EPOCH)
}

/// Parse a VARCHAR string representation into a `TypedValue` based on the DDL-time type_id.
///
/// Called after reading all columns as VARCHAR strings from the result chunks.
/// Empty strings are treated as NULL for numeric types.
fn parse_typed_from_str(s: &str, type_id: u32) -> TypedValue {
    use ffi::{
        DUCKDB_TYPE_DUCKDB_TYPE_BIGINT as BIGINT, DUCKDB_TYPE_DUCKDB_TYPE_DATE as DATE,
        DUCKDB_TYPE_DUCKDB_TYPE_DECIMAL as DECIMAL, DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE as DOUBLE,
        DUCKDB_TYPE_DUCKDB_TYPE_FLOAT as FLOAT, DUCKDB_TYPE_DUCKDB_TYPE_HUGEINT as HUGEINT,
        DUCKDB_TYPE_DUCKDB_TYPE_INTEGER as INTEGER, DUCKDB_TYPE_DUCKDB_TYPE_SMALLINT as SMALLINT,
        DUCKDB_TYPE_DUCKDB_TYPE_TIMESTAMP as TIMESTAMP, DUCKDB_TYPE_DUCKDB_TYPE_TINYINT as TINYINT,
        DUCKDB_TYPE_DUCKDB_TYPE_UBIGINT as UBIGINT, DUCKDB_TYPE_DUCKDB_TYPE_UINTEGER as UINTEGER,
        DUCKDB_TYPE_DUCKDB_TYPE_USMALLINT as USMALLINT,
        DUCKDB_TYPE_DUCKDB_TYPE_UTINYINT as UTINYINT,
    };

    if s.is_empty() {
        return TypedValue::Null;
    }

    match type_id {
        // 64-bit integer types: parse as i64.
        BIGINT | UBIGINT | TIMESTAMP | HUGEINT => s
            .parse::<i64>()
            .map(TypedValue::I64)
            .unwrap_or(TypedValue::Null),
        // DATE: "YYYY-MM-DD" → days since 1970-01-01 stored as i32.
        DATE => date_str_to_epoch_days(s)
            .map(TypedValue::I32)
            .unwrap_or(TypedValue::Null),
        // 32-bit integer types.
        INTEGER | UINTEGER | SMALLINT | TINYINT | USMALLINT | UTINYINT => s
            .parse::<i32>()
            .map(TypedValue::I32)
            .unwrap_or(TypedValue::Null),
        // Floating-point types: parse as f64.
        DOUBLE | FLOAT => s
            .parse::<f64>()
            .map(TypedValue::F64)
            .unwrap_or(TypedValue::Null),
        // DECIMAL: keep as string to preserve exact precision formatting ("350.00" not "350.0").
        DECIMAL => TypedValue::Str(s.to_owned()),
        // VARCHAR and all other types: preserve as string.
        _ => TypedValue::Str(s.to_owned()),
    }
}

/// Write a collected column of `TypedValue`s into the output `DataChunkHandle`.
///
/// Dispatches based on `type_id` to write typed scalar data via `as_mut_slice_with_len`.
/// NULL values are written via `set_null`. VARCHAR fallback uses `insert`.
fn write_typed_column(
    output: &mut DataChunkHandle,
    col_idx: usize,
    values: &[TypedValue],
    n_rows: usize,
    type_id: u32,
) {
    use ffi::{
        DUCKDB_TYPE_DUCKDB_TYPE_BIGINT as BIGINT, DUCKDB_TYPE_DUCKDB_TYPE_DATE as DATE,
        DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE as DOUBLE, DUCKDB_TYPE_DUCKDB_TYPE_FLOAT as FLOAT,
        DUCKDB_TYPE_DUCKDB_TYPE_HUGEINT as HUGEINT, DUCKDB_TYPE_DUCKDB_TYPE_INTEGER as INTEGER,
        DUCKDB_TYPE_DUCKDB_TYPE_SMALLINT as SMALLINT,
        DUCKDB_TYPE_DUCKDB_TYPE_TIMESTAMP as TIMESTAMP, DUCKDB_TYPE_DUCKDB_TYPE_TINYINT as TINYINT,
        DUCKDB_TYPE_DUCKDB_TYPE_UBIGINT as UBIGINT, DUCKDB_TYPE_DUCKDB_TYPE_UINTEGER as UINTEGER,
        DUCKDB_TYPE_DUCKDB_TYPE_USMALLINT as USMALLINT,
        DUCKDB_TYPE_DUCKDB_TYPE_UTINYINT as UTINYINT,
    };

    let mut out_vec = output.flat_vector(col_idx);

    match type_id {
        BIGINT | UBIGINT | TIMESTAMP | HUGEINT => {
            // Collect null positions before taking the slice borrow.
            let null_positions: Vec<usize> = values
                .iter()
                .enumerate()
                .filter_map(|(i, v)| matches!(v, TypedValue::Null).then_some(i))
                .collect();
            {
                let dst = out_vec.as_mut_slice_with_len::<i64>(n_rows);
                for (i, val) in values.iter().enumerate() {
                    dst[i] = if let TypedValue::I64(v) = val { *v } else { 0 };
                }
            } // dst borrow released here
            for i in null_positions {
                out_vec.set_null(i);
            }
        }

        INTEGER | UINTEGER | SMALLINT | TINYINT | USMALLINT | UTINYINT | DATE => {
            let null_positions: Vec<usize> = values
                .iter()
                .enumerate()
                .filter_map(|(i, v)| matches!(v, TypedValue::Null).then_some(i))
                .collect();
            {
                let dst = out_vec.as_mut_slice_with_len::<i32>(n_rows);
                for (i, val) in values.iter().enumerate() {
                    dst[i] = if let TypedValue::I32(v) = val { *v } else { 0 };
                }
            }
            for i in null_positions {
                out_vec.set_null(i);
            }
        }

        DOUBLE | FLOAT => {
            let null_positions: Vec<usize> = values
                .iter()
                .enumerate()
                .filter_map(|(i, v)| matches!(v, TypedValue::Null).then_some(i))
                .collect();
            {
                let dst = out_vec.as_mut_slice_with_len::<f64>(n_rows);
                for (i, val) in values.iter().enumerate() {
                    dst[i] = if let TypedValue::F64(v) = val {
                        *v
                    } else {
                        0.0
                    };
                }
            }
            for i in null_positions {
                out_vec.set_null(i);
            }
        }

        _ => {
            // VARCHAR and all fallback types: insert as strings.
            for (i, val) in values.iter().enumerate() {
                match val {
                    TypedValue::Str(s) => out_vec.insert(i, s.as_str()),
                    TypedValue::Null => out_vec.insert(i, ""),
                    TypedValue::I64(v) => out_vec.insert(i, &v.to_string()),
                    TypedValue::I32(v) => out_vec.insert(i, &v.to_string()),
                    TypedValue::F64(v) => out_vec.insert(i, &v.to_string()),
                }
            }
        }
    }
}
