use std::collections::HashMap;
use std::ffi::{CStr, CString};
use std::os::raw::c_void;
use std::sync::Mutex;

use duckdb::{
    core::{DataChunkHandle, LogicalTypeHandle, LogicalTypeId},
    vtab::{BindInfo, InitInfo, TableFunctionInfo, VTab, Value},
};
use libduckdb_sys as ffi;

use crate::catalog::CatalogState;
use crate::expand::{expand, suggest_closest, QueryRequest};
use crate::model::SemanticViewDefinition;

use super::error::QueryError;

// ---------------------------------------------------------------------------
// QueryState -- stored as extra_info on the table function
// ---------------------------------------------------------------------------

/// Shared state for the `semantic_query` table function.
///
/// Carries the catalog (in-memory view definitions) and a raw `duckdb_connection`
/// handle for executing expanded SQL via the C API. The connection is created
/// independently of the host connection by calling `duckdb_connect` on the same
/// database handle, avoiding lock conflicts with the host during query execution.
///
/// For the connection handle extraction strategy, see `extract_query_conn` in lib.rs.
#[derive(Clone)]
pub struct QueryState {
    pub catalog: CatalogState,
    /// Raw connection handle for SQL execution.
    pub conn: ffi::duckdb_connection,
}

// SAFETY: The `duckdb_connection` raw pointer is an opaque handle managed by DuckDB.
// It was created during `extension_entrypoint` and lives for the database session lifetime.
// DuckDB manages internal synchronization for connections.
unsafe impl Send for QueryState {}
unsafe impl Sync for QueryState {}

// ---------------------------------------------------------------------------
// BindData / InitData
// ---------------------------------------------------------------------------

/// Data computed at bind time: the expanded SQL, output schema, and metadata.
pub struct SemanticViewBindData {
    /// The SQL query generated by `expand()`, ready for display (e.g., EXPLAIN).
    expanded_sql: String,
    /// The SQL actually executed at query time. May wrap `expanded_sql` with
    /// explicit type casts to ensure runtime column types match bind declarations
    /// (handles HUGEINT→BIGINT optimizer changes and STRUCT/MAP→VARCHAR).
    execution_sql: String,
    /// Output column names (dimensions first, then metrics).
    column_names: Vec<String>,
    /// DuckDB type enums (as u32) for each output column, parallel to column_names.
    /// `DUCKDB_TYPE_INVALID` (0) signals VARCHAR fallback for that column.
    /// Retained for diagnostic purposes (e.g., future EXPLAIN enhancements).
    #[allow(dead_code)]
    column_type_ids: Vec<u32>,
}

// SAFETY: All fields are `Send + Sync` types.
unsafe impl Send for SemanticViewBindData {}
unsafe impl Sync for SemanticViewBindData {}

/// Mutable state for streaming result chunks during query execution.
struct StreamingState {
    result: ffi::duckdb_result,
    chunk_count: usize,
    col_count: usize,
    current_chunk: usize,
}

// SAFETY: duckdb_result contains raw pointers but is only accessed single-threaded
// through the Mutex in func() calls. DuckDB table functions run on a single thread
// per scan.
unsafe impl Send for StreamingState {}

impl Drop for StreamingState {
    fn drop(&mut self) {
        unsafe { ffi::duckdb_destroy_result(&mut self.result) }
    }
}

/// State tracked during function execution.
pub struct SemanticViewInitData {
    /// Streaming state: `None` before first `func()` call, `Some` during streaming.
    inner: Mutex<Option<StreamingState>>,
}

// SAFETY: Mutex provides interior mutability; StreamingState is Send.
unsafe impl Send for SemanticViewInitData {}
unsafe impl Sync for SemanticViewInitData {}

// ---------------------------------------------------------------------------
// FFI helpers
// ---------------------------------------------------------------------------

/// Execute a SQL string via the DuckDB C API and return the result.
///
/// The caller is responsible for calling `duckdb_destroy_result` on the returned
/// result when done.
///
/// # Safety
///
/// `conn` must be a valid, non-null `duckdb_connection` handle.
pub(crate) unsafe fn execute_sql_raw(
    conn: ffi::duckdb_connection,
    sql: &str,
) -> Result<ffi::duckdb_result, String> {
    let sql_cstr = CString::new(sql).map_err(|e| e.to_string())?;
    let mut result: ffi::duckdb_result = std::mem::zeroed();
    let rc = ffi::duckdb_query(conn, sql_cstr.as_ptr(), &mut result);
    if rc != ffi::DuckDBSuccess {
        let err_ptr = ffi::duckdb_result_error(&mut result);
        let err_msg = if err_ptr.is_null() {
            "unknown error".to_string()
        } else {
            CStr::from_ptr(err_ptr).to_string_lossy().into_owned()
        };
        ffi::duckdb_destroy_result(&mut result);
        return Err(err_msg);
    }
    Ok(result)
}

/// Extract the raw `duckdb_value` pointer from a `duckdb::vtab::Value`.
///
/// The `Value` struct has a single field `ptr: duckdb_value` (which is `*mut c_void`),
/// but it is `pub(crate)` and inaccessible from external crates.  Since both types
/// are exactly one pointer wide, transmute is a safe layout conversion.
///
/// The returned pointer is valid only for the lifetime of the `Value` (it is NOT
/// destroyed; the `Value` still owns it).
///
/// # Safety
///
/// Relies on `duckdb::vtab::Value` layout being a single `duckdb_value` field.
/// This is stable for `duckdb = "=1.4.4"`.
unsafe fn value_raw_ptr(value: &Value) -> ffi::duckdb_value {
    // Value is repr(Rust) with one field: duckdb_value (*mut c_void).
    // Reading the pointer without taking ownership.
    let ptr_to_value = std::ptr::from_ref(value).cast::<ffi::duckdb_value>();
    std::ptr::read(ptr_to_value)
}

/// Extract string elements from a DuckDB LIST(VARCHAR) value.
///
/// Uses the C API `duckdb_get_list_size` and `duckdb_get_list_child` to iterate
/// the list, then `duckdb_get_varchar` on each child element.
///
/// # Safety
///
/// `value` must represent a LIST(VARCHAR) value.
pub(crate) unsafe fn extract_list_strings(value: &Value) -> Vec<String> {
    let value_ptr = value_raw_ptr(value);
    let size = ffi::duckdb_get_list_size(value_ptr);
    let mut result = Vec::with_capacity(size as usize);
    for i in 0..size {
        let child = ffi::duckdb_get_list_child(value_ptr, i);
        let cstr = ffi::duckdb_get_varchar(child);
        if !cstr.is_null() {
            let s = CStr::from_ptr(cstr).to_string_lossy().into_owned();
            ffi::duckdb_free(cstr.cast::<c_void>());
            result.push(s);
        }
        ffi::duckdb_destroy_value(&mut { child });
    }
    result
}

/// Extract key-value pairs from a DuckDB MAP(VARCHAR, VARCHAR) named parameter value.
///
/// Returns a `HashMap` with all keys lowercased for case-insensitive dimension name
/// matching. Only entries where both key and value are non-null are inserted.
///
/// # Safety
///
/// `value` must represent a MAP(VARCHAR, VARCHAR) value.
unsafe fn extract_map_strings(value: &Value) -> HashMap<String, String> {
    let value_ptr = value_raw_ptr(value);
    let size = ffi::duckdb_get_map_size(value_ptr);
    let mut result = HashMap::with_capacity(size as usize);
    for i in 0..size {
        let mut key = ffi::duckdb_get_map_key(value_ptr, i);
        let mut val = ffi::duckdb_get_map_value(value_ptr, i);
        let k_cstr = ffi::duckdb_get_varchar(key);
        let v_cstr = ffi::duckdb_get_varchar(val);
        if !k_cstr.is_null() && !v_cstr.is_null() {
            let k = CStr::from_ptr(k_cstr).to_string_lossy().into_owned();
            let v = CStr::from_ptr(v_cstr).to_string_lossy().into_owned();
            ffi::duckdb_free(k_cstr.cast::<c_void>());
            ffi::duckdb_free(v_cstr.cast::<c_void>());
            result.insert(k.to_ascii_lowercase(), v);
        }
        ffi::duckdb_destroy_value(&mut key);
        ffi::duckdb_destroy_value(&mut val);
    }
    result
}

// ---------------------------------------------------------------------------
// Type mapping helpers
// ---------------------------------------------------------------------------

/// RAII wrapper for `ffi::duckdb_logical_type` handles.
///
/// Automatically calls `duckdb_destroy_logical_type` when dropped.
struct LogicalTypeOwned(ffi::duckdb_logical_type);

impl Drop for LogicalTypeOwned {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { ffi::duckdb_destroy_logical_type(&mut self.0) };
        }
    }
}

/// Normalize HUGEINT/UHUGEINT type IDs to BIGINT/UBIGINT.
///
/// DuckDB's query planner infers `sum()` as HUGEINT at LIMIT-0 time, but the
/// runtime optimizer may substitute `sum_no_overflow` → BIGINT (8 bytes/value).
/// Normalizing stored type IDs prevents stale HUGEINT values from propagating
/// into output declarations.
pub(crate) fn normalize_type_id(t: u32) -> u32 {
    const HUGEINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_HUGEINT;
    const UHUGEINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_UHUGEINT;
    const BIGINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT;
    const UBIGINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_UBIGINT;
    match t {
        HUGEINT => BIGINT,
        UHUGEINT => UBIGINT,
        _ => t,
    }
}

/// Convert a raw `ffi::duckdb_type` (u32) to a `LogicalTypeHandle`.
///
/// DECIMAL, LIST, ENUM, and STRUCT/MAP/complex types need the logical type handle
/// for accurate metadata; they are handled separately via `declare_output_type`.
/// INVALID (0) falls back to VARCHAR.
fn type_from_duckdb_type_u32(t: u32) -> LogicalTypeHandle {
    // Named constants matching libduckdb-sys DUCKDB_TYPE_DUCKDB_TYPE_* values.
    const INVALID: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_INVALID;
    const STRUCT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_STRUCT;
    const MAP: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_MAP;
    match t {
        // Complex types with no flat binary representation fall back to VARCHAR.
        INVALID | STRUCT | MAP => LogicalTypeHandle::from(LogicalTypeId::Varchar),
        // All other types map directly via the type_id.
        // Note: HUGEINT/UHUGEINT should already be normalized to BIGINT/UBIGINT
        // via normalize_type_id() before reaching here.
        _ => LogicalTypeHandle::from(LogicalTypeId::from(t)),
    }
}

/// Declare the output type for a column, using logical type metadata for DECIMAL/LIST/ENUM.
///
/// For complex types that need logical type metadata (DECIMAL width/scale, LIST child type,
/// ENUM → VARCHAR), this function reads the metadata and returns the correct output type.
/// All other types delegate to `type_from_duckdb_type_u32`.
///
/// # Safety
///
/// `logical_type` must be a valid `duckdb_logical_type` handle for column `type_id`.
unsafe fn declare_output_type(
    logical_type: ffi::duckdb_logical_type,
    type_id: u32,
) -> LogicalTypeHandle {
    const DECIMAL: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_DECIMAL;
    const LIST: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_LIST;
    const ENUM: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_ENUM;

    match type_id {
        DECIMAL => {
            let width = ffi::duckdb_decimal_width(logical_type);
            let scale = ffi::duckdb_decimal_scale(logical_type);
            LogicalTypeHandle::decimal(width, scale)
        }
        LIST => {
            let child_lt = LogicalTypeOwned(ffi::duckdb_list_type_child_type(logical_type));
            let child_type_id = ffi::duckdb_get_type_id(child_lt.0) as u32;
            let child_lth = LogicalTypeHandle::from(LogicalTypeId::from(child_type_id));
            LogicalTypeHandle::list(&child_lth)
        }
        ENUM => {
            // ENUM output is declared as VARCHAR — users see string values, not ordinals.
            LogicalTypeHandle::from(LogicalTypeId::Varchar)
        }
        _ => type_from_duckdb_type_u32(type_id),
    }
}

// ---------------------------------------------------------------------------
// Execution SQL generation
// ---------------------------------------------------------------------------

/// Build the SQL used at execution time, wrapping the expanded SQL with explicit
/// type casts for columns whose runtime type may differ from the bind declaration.
///
/// This handles two known mismatches:
/// 1. HUGEINT→BIGINT / UHUGEINT→UBIGINT: DuckDB's optimizer may change `sum()`
///    return types between LIMIT-0 planning and actual execution. The cast ensures
///    the result always matches the bind-declared type.
/// 2. STRUCT/MAP→VARCHAR: These complex types are declared as VARCHAR at bind time.
///    The cast produces a string representation at runtime.
///
/// For all other types, columns pass through unmodified. If no columns need casting,
/// the original expanded SQL is returned as-is (no wrapper overhead).
fn build_execution_sql(
    expanded_sql: &str,
    column_names: &[String],
    column_type_ids: &[u32],
) -> String {
    const BIGINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT;
    const UBIGINT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_UBIGINT;
    const STRUCT: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_STRUCT;
    const MAP: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_MAP;
    const INVALID: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_INVALID;

    let needs_wrapping = column_type_ids
        .iter()
        .any(|&t| matches!(t, BIGINT | UBIGINT | STRUCT | MAP | INVALID));

    if !needs_wrapping {
        return expanded_sql.to_string();
    }

    let clauses: Vec<String> = column_names
        .iter()
        .zip(column_type_ids.iter())
        .map(|(name, &tid)| {
            let cast_type = match tid {
                BIGINT => Some("BIGINT"),
                UBIGINT => Some("UBIGINT"),
                STRUCT | MAP | INVALID => Some("VARCHAR"),
                _ => None,
            };
            match cast_type {
                Some(ty) => format!("\"{name}\"::{ty} AS \"{name}\""),
                None => format!("\"{name}\""),
            }
        })
        .collect();

    format!(
        "SELECT {} FROM ({expanded_sql}) __sv_inner",
        clauses.join(", ")
    )
}

// ---------------------------------------------------------------------------
// VTab implementation
// ---------------------------------------------------------------------------

/// The `semantic_query` table function.
///
/// Registered as a single generic function that accepts a view name as a
/// positional parameter and optional `dimensions` / `metrics` as named
/// `LIST(VARCHAR)` parameters.
///
/// Usage:
/// ```sql
/// FROM semantic_query('my_view', dimensions := ['region'], metrics := ['total_revenue'])
/// ```
pub struct SemanticViewVTab;

impl VTab for SemanticViewVTab {
    type BindData = SemanticViewBindData;
    type InitData = SemanticViewInitData;

    fn bind(bind: &BindInfo) -> Result<Self::BindData, Box<dyn std::error::Error>> {
        // 1. Extract the view name (positional parameter 0).
        let view_name = bind.get_parameter(0).to_string();

        // 2. Extract dimensions and metrics from named LIST(VARCHAR) parameters.
        //    Use the raw duckdb_value FFI to iterate list elements.
        let dimensions = match bind.get_named_parameter("dimensions") {
            Some(ref val) => unsafe { extract_list_strings(val) },
            None => vec![],
        };
        let metrics = match bind.get_named_parameter("metrics") {
            Some(ref val) => unsafe { extract_list_strings(val) },
            None => vec![],
        };

        // Extract optional granularities MAP(VARCHAR, VARCHAR) for query-time override (TIME-03).
        let granularity_overrides: HashMap<String, String> =
            match bind.get_named_parameter("granularities") {
                Some(ref val) => unsafe { extract_map_strings(val) },
                None => HashMap::new(),
            };

        // 3. Validate: at least one dimension or metric.
        if dimensions.is_empty() && metrics.is_empty() {
            return Err(Box::new(QueryError::EmptyRequest {
                view_name: view_name.clone(),
            }));
        }

        // 4. Look up view definition in the catalog.
        let state_ptr = bind.get_extra_info::<QueryState>();
        let state = unsafe { &*state_ptr };
        let catalog_guard = state.catalog.read().expect("catalog RwLock poisoned");

        let json_str = match catalog_guard.get(&view_name) {
            Some(j) => j.clone(),
            None => {
                let available: Vec<String> = catalog_guard.keys().cloned().collect();
                let suggestion = suggest_closest(&view_name, &available);
                return Err(Box::new(QueryError::ViewNotFound {
                    name: view_name,
                    suggestion,
                    available,
                }));
            }
        };
        // Release the catalog lock before proceeding.
        drop(catalog_guard);

        // 5. Parse definition and expand.
        let def = SemanticViewDefinition::from_json(&view_name, &json_str)
            .map_err(|e| -> Box<dyn std::error::Error> { e.into() })?;

        // Validate granularity overrides against the view definition (TIME-03).
        const VALID_GRANULARITIES: &[&str] = &["day", "week", "month", "year"];
        for (override_dim_lower, override_gran) in &granularity_overrides {
            if let Some(dim_def) = def
                .dimensions
                .iter()
                .find(|d| d.name.to_ascii_lowercase() == *override_dim_lower)
            {
                if dim_def.dim_type.as_deref() != Some("time") {
                    return Err(format!(
                        "dimension '{}' is not a time dimension and cannot have a granularity override",
                        dim_def.name
                    )
                    .into());
                }
                if !VALID_GRANULARITIES.contains(&override_gran.as_str()) {
                    return Err(format!(
                        "granularity override '{}' for dimension '{}' is not supported; valid values: {}",
                        override_gran,
                        dim_def.name,
                        VALID_GRANULARITIES.join(", ")
                    )
                    .into());
                }
            }
            // If dimension doesn't exist in the view at all, expand() will catch it as UnknownDimension.
        }

        let req = QueryRequest {
            dimensions: dimensions.clone(),
            metrics: metrics.clone(),
            granularity_overrides,
        };
        let expanded_sql = expand(&view_name, &def, &req)
            .map_err(|e| -> Box<dyn std::error::Error> { Box::new(QueryError::from(e)) })?;

        // 6. Resolve output column names and types.
        //    Primary path: use DDL-time stored type data (column_type_names + column_types_inferred).
        //    Fallback path: run LIMIT 0 at bind time (in-memory DB or inference failed at DDL time).
        //    Full fallback: derive names from definition, all VARCHAR.
        let type_map: HashMap<String, u32> = def
            .column_type_names
            .iter()
            .zip(def.column_types_inferred.iter())
            .map(|(name, &t)| (name.to_ascii_lowercase(), normalize_type_id(t)))
            .collect();

        let (column_names, column_type_ids) = if !type_map.is_empty() {
            // Primary path: DDL-time inference stored both names and types.
            // Derive column names from requested dims+metrics (expand() order),
            // look up each name in the DDL-time type map. No LIMIT 0 at query time.
            let mut names = Vec::new();
            let mut type_ids = Vec::new();
            for dim_name in &dimensions {
                let canonical = def
                    .dimensions
                    .iter()
                    .find(|d| d.name.eq_ignore_ascii_case(dim_name))
                    .map_or_else(|| dim_name.clone(), |d| d.name.clone());
                let t = *type_map
                    .get(&canonical.to_ascii_lowercase())
                    .unwrap_or(&0u32);
                names.push(canonical);
                type_ids.push(t);
            }
            for met_name in &metrics {
                let canonical = def
                    .metrics
                    .iter()
                    .find(|m| m.name.eq_ignore_ascii_case(met_name))
                    .map_or_else(|| met_name.clone(), |m| m.name.clone());
                let t = *type_map
                    .get(&canonical.to_ascii_lowercase())
                    .unwrap_or(&0u32);
                names.push(canonical);
                type_ids.push(t);
            }
            (names, type_ids)
        } else {
            // Fallback path: in-memory DB or DDL inference failed.
            // Run try_infer_schema on the per-query expanded SQL (bind-time, safe on state.conn).
            let limit0_sql = format!("{expanded_sql} LIMIT 0");
            if let Some((names, types)) = unsafe { try_infer_schema(state.conn, &limit0_sql) } {
                let type_ids: Vec<u32> =
                    types.iter().map(|t| normalize_type_id(*t as u32)).collect();
                (names, type_ids)
            } else {
                // Full fallback: derive names from definition, all VARCHAR (0 = INVALID).
                let mut names = Vec::new();
                for dim_name in &dimensions {
                    let canonical = def
                        .dimensions
                        .iter()
                        .find(|d| d.name.eq_ignore_ascii_case(dim_name))
                        .map_or_else(|| dim_name.clone(), |d| d.name.clone());
                    names.push(canonical);
                }
                for met_name in &metrics {
                    let canonical = def
                        .metrics
                        .iter()
                        .find(|m| m.name.eq_ignore_ascii_case(met_name))
                        .map_or_else(|| met_name.clone(), |m| m.name.clone());
                    names.push(canonical);
                }
                let type_ids = vec![0u32; names.len()];
                (names, type_ids)
            }
        };

        // 7. Declare typed output columns.
        //    For DECIMAL/LIST/ENUM: we need the logical type for metadata.
        //    Check if any column requires a LIMIT-0 query for logical type metadata.
        const DECIMAL: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_DECIMAL;
        const LIST: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_LIST;
        const ENUM: u32 = ffi::DUCKDB_TYPE_DUCKDB_TYPE_ENUM;

        let needs_logical_types = column_type_ids
            .iter()
            .any(|&t| t == DECIMAL || t == LIST || t == ENUM);

        if needs_logical_types {
            // Run a LIMIT 0 query to get logical type handles for columns that need them.
            let limit0_sql = format!("{expanded_sql} LIMIT 0");
            if let Ok(mut limit0_result) = unsafe { execute_sql_raw(state.conn, &limit0_sql) } {
                for (name, &type_id) in column_names.iter().zip(column_type_ids.iter()) {
                    let col_pos =
                        column_names.iter().position(|n| n == name).unwrap_or(0) as ffi::idx_t;
                    if type_id == DECIMAL || type_id == LIST || type_id == ENUM {
                        let lt = LogicalTypeOwned(unsafe {
                            ffi::duckdb_column_logical_type(&mut limit0_result, col_pos)
                        });
                        let out_type = unsafe { declare_output_type(lt.0, type_id) };
                        bind.add_result_column(name, out_type);
                    } else {
                        bind.add_result_column(name, type_from_duckdb_type_u32(type_id));
                    }
                }
                unsafe { ffi::duckdb_destroy_result(&mut limit0_result) };
            } else {
                // LIMIT 0 failed — fall back to basic type mapping for all columns.
                for (name, &type_id) in column_names.iter().zip(column_type_ids.iter()) {
                    bind.add_result_column(name, type_from_duckdb_type_u32(type_id));
                }
            }
        } else {
            // No DECIMAL/LIST/ENUM — fast path, no LIMIT 0 needed.
            for (name, &type_id) in column_names.iter().zip(column_type_ids.iter()) {
                bind.add_result_column(name, type_from_duckdb_type_u32(type_id));
            }
        }

        // 8. Build execution SQL with type casts for columns that may have
        //    runtime type mismatches (HUGEINT→BIGINT, STRUCT/MAP→VARCHAR).
        let execution_sql = build_execution_sql(&expanded_sql, &column_names, &column_type_ids);

        Ok(SemanticViewBindData {
            expanded_sql,
            execution_sql,
            column_names,
            column_type_ids,
        })
    }

    fn init(_: &InitInfo) -> Result<Self::InitData, Box<dyn std::error::Error>> {
        Ok(SemanticViewInitData {
            inner: Mutex::new(None),
        })
    }

    fn func(
        func: &TableFunctionInfo<Self>,
        output: &mut DataChunkHandle,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let init_data = func.get_init_data();
        let bind_data = func.get_bind_data();

        let mut guard = init_data.inner.lock().unwrap();

        // First call: execute the query and store the result for streaming.
        if guard.is_none() {
            let state = unsafe { &*func.get_extra_info::<QueryState>() };
            let mut result = unsafe {
                execute_sql_raw(state.conn, &bind_data.execution_sql).map_err(|e| {
                    QueryError::SqlExecution {
                        expanded_sql: bind_data.expanded_sql.clone(),
                        duckdb_error: e,
                    }
                })?
            };
            let chunk_count = unsafe { ffi::duckdb_result_chunk_count(result) } as usize;
            let col_count = unsafe { ffi::duckdb_column_count(&mut result) } as usize;
            *guard = Some(StreamingState {
                result,
                chunk_count,
                col_count,
                current_chunk: 0,
            });
        }

        let streaming = guard.as_mut().unwrap();

        // All chunks consumed — signal end of stream.
        if streaming.current_chunk >= streaming.chunk_count {
            output.set_len(0);
            return Ok(());
        }

        // Get the next source chunk.
        let src_chunk = unsafe {
            ffi::duckdb_result_get_chunk(streaming.result, streaming.current_chunk as ffi::idx_t)
        };
        streaming.current_chunk += 1;

        if src_chunk.is_null() {
            output.set_len(0);
            return Ok(());
        }

        let row_count = unsafe { ffi::duckdb_data_chunk_get_size(src_chunk) } as usize;
        if row_count == 0 {
            unsafe { ffi::duckdb_destroy_data_chunk(&mut { src_chunk }) };
            output.set_len(0);
            return Ok(());
        }

        // Zero-copy transfer: reference each source vector into the output chunk.
        // After duckdb_vector_reference_vector, both vectors share ownership of the
        // underlying data buffer, so the source chunk can be safely destroyed.
        let out_ptr = output.get_ptr();
        let n_cols = streaming.col_count.min(bind_data.column_names.len());
        for col_idx in 0..n_cols {
            let src_vec =
                unsafe { ffi::duckdb_data_chunk_get_vector(src_chunk, col_idx as ffi::idx_t) };
            let dst_vec =
                unsafe { ffi::duckdb_data_chunk_get_vector(out_ptr, col_idx as ffi::idx_t) };
            unsafe { ffi::duckdb_vector_reference_vector(dst_vec, src_vec) };
        }
        output.set_len(row_count);

        // Source chunk can be destroyed — vectors share ownership via reference.
        unsafe { ffi::duckdb_destroy_data_chunk(&mut { src_chunk }) };

        Ok(())
    }

    fn parameters() -> Option<Vec<LogicalTypeHandle>> {
        // Positional parameter: view_name (VARCHAR)
        Some(vec![LogicalTypeHandle::from(LogicalTypeId::Varchar)])
    }

    fn named_parameters() -> Option<Vec<(String, LogicalTypeHandle)>> {
        Some(vec![
            (
                "dimensions".to_string(),
                LogicalTypeHandle::list(&LogicalTypeHandle::from(LogicalTypeId::Varchar)),
            ),
            (
                "metrics".to_string(),
                LogicalTypeHandle::list(&LogicalTypeHandle::from(LogicalTypeId::Varchar)),
            ),
            // granularities: query-time granularity override map (TIME-03)
            // MAP(VARCHAR, VARCHAR) — e.g., granularities := {'order_date': 'month'}
            (
                "granularities".to_string(),
                LogicalTypeHandle::map(
                    &LogicalTypeHandle::from(LogicalTypeId::Varchar),
                    &LogicalTypeHandle::from(LogicalTypeId::Varchar),
                ),
            ),
        ])
    }
}

// ---------------------------------------------------------------------------
// Schema inference
// ---------------------------------------------------------------------------

/// Attempt to infer column names and types by executing a LIMIT 0 query.
///
/// Returns `None` if the query fails for any reason.
///
/// # Safety
///
/// `conn` must be a valid `duckdb_connection`.
pub(crate) unsafe fn try_infer_schema(
    conn: ffi::duckdb_connection,
    sql: &str,
) -> Option<(Vec<String>, Vec<ffi::duckdb_type>)> {
    let mut result = execute_sql_raw(conn, sql).ok()?;

    let col_count = ffi::duckdb_column_count(&mut result) as usize;
    let mut names = Vec::with_capacity(col_count);
    let mut types = Vec::with_capacity(col_count);

    for i in 0..col_count {
        let name_ptr = ffi::duckdb_column_name(&mut result, i as ffi::idx_t);
        let name = if name_ptr.is_null() {
            format!("column{i}")
        } else {
            CStr::from_ptr(name_ptr).to_string_lossy().into_owned()
        };
        names.push(name);

        let ty = ffi::duckdb_column_type(&mut result, i as ffi::idx_t);
        types.push(ty);
    }

    ffi::duckdb_destroy_result(&mut result);
    Some((names, types))
}

// ---------------------------------------------------------------------------
// VARCHAR reading (used by explain.rs)
// ---------------------------------------------------------------------------

/// Read a VARCHAR value from a data chunk vector at the given column and row.
///
/// The vector must contain VARCHAR (`duckdb_string_t`) data. Returns an empty
/// string for NULL values.
///
/// Decodes the `duckdb_string_t` layout directly from vector memory to avoid
/// reliance on C API helper functions that may not be available in loadable
/// extension mode.
///
/// # Safety
///
/// `chunk` must be a valid, non-null `duckdb_data_chunk` handle.
/// `col_idx` and `row_idx` must be within bounds.
#[allow(clippy::cast_possible_truncation)]
pub(crate) unsafe fn read_varchar_from_vector(
    chunk: ffi::duckdb_data_chunk,
    col_idx: usize,
    row_idx: usize,
) -> String {
    let vector = ffi::duckdb_data_chunk_get_vector(chunk, col_idx as ffi::idx_t);

    // Check for NULL using the validity mask.
    let validity = ffi::duckdb_vector_get_validity(vector);
    if !validity.is_null() {
        let entry_idx = row_idx / 64;
        let bit_idx = row_idx % 64;
        let entry = *validity.add(entry_idx);
        if entry & (1u64 << bit_idx) == 0 {
            return String::new(); // NULL
        }
    }

    // Read the duckdb_string_t from the vector data.
    // Layout is a 16-byte union:
    //   Inline  (len <= 12): { length: u32, inlined: [c_char; 12] }
    //   Pointer (len > 12):  { length: u32, prefix: [c_char; 4], ptr: *mut c_char }
    let data_ptr = ffi::duckdb_vector_get_data(vector);
    let string_t_ptr = data_ptr.cast::<ffi::duckdb_string_t>().add(row_idx);
    let string_t = &*string_t_ptr;

    // The length field is at the same offset for both union variants.
    let len = string_t.value.inlined.length as usize;
    if len == 0 {
        return String::new();
    }

    let bytes = if len <= 12 {
        // Inline: string data follows the length field directly.
        let inline_ptr = string_t.value.inlined.inlined.as_ptr().cast::<u8>();
        std::slice::from_raw_parts(inline_ptr, len)
    } else {
        // Pointer: data is at the heap-allocated ptr.
        let heap_ptr = string_t.value.pointer.ptr.cast::<u8>();
        if heap_ptr.is_null() {
            return String::new();
        }
        std::slice::from_raw_parts(heap_ptr, len)
    };

    String::from_utf8_lossy(bytes).into_owned()
}
